# -*- coding: utf-8 -*-
"""walkthrough.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdF9WYQKY7R62BcAK-NVZNhLcYuYEWEE
"""

# Colab cell 1: Install dependencies
!pip install --quiet diffusers transformers accelerate safetensors

#  2: Imports & Auth
import time, torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler, PNDMScheduler
from huggingface_hub import login

# Authenticate (paste your token in the prompt)
token = input("")
login(token, add_to_git_credential=False)

#  3: Load & tweak pipeline
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_auth_token=True
).to("cuda")

# Swap scheduler to DPM-Solver for faster high-quality sampling
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)

# 4 Generation function
def gen_image(prompt, seed, guidance, steps, width=512, height=512, negative=None):
    torch.cuda.empty_cache()
    gen = torch.Generator(device="cuda").manual_seed(seed)
    start = time.time()
    out = pipe(
        prompt,
        negative_prompt=negative,
        width=width, height=height,
        guidance_scale=guidance,
        num_inference_steps=steps,
        generator=gen
    ).images[0]
    print(f"→ Seed={seed}, guide={guidance}, steps={steps}, {width}×{height} in {time.time()-start:.1f}s")
    display(out)
    return out

#5: Example configs
configs = [
    {"prompt":"A serene mountain lake at sunrise","seed":42,  "guidance":7.5,"steps":30},
    {"prompt":"A serene mountain lake at sunrise","seed":42,  "guidance":12.0,"steps":30},
    {"prompt":"A serene mountain lake at sunrise","seed":999, "guidance":7.5,"steps":30},
    {"prompt":"A serene mountain lake at sunrise","seed":42,  "guidance":7.5,"steps":50},
    {"prompt":"A serene mountain lake at sunrise","seed":42,  "guidance":7.5,"steps":30,"width":768,"height":768},
    {"prompt":"A serene mountain lake at sunrise","seed":42,  "guidance":7.5,"steps":30,"negative":"lowres, blurry"}
]

# 6: Run walkthrough
for cfg in configs:
    gen_image(**cfg)
